### PR TITLE
Add compilation flags for DataFusion

### PR DESCRIPTION
**Pull request by Dandandan**
This builds the release with LTO.

### CODE REVIEW

**Comment by Dandandan** [comment]
FYI @waitingkuo

**Comment by waitingkuo** [comment]
@Dandandan thank you! Do you think we should fix the version as datafusion v11 just released. I used master since v10 has some issues to pass the tests

**Comment by Dandandan** [comment]
> @Dandandan thank you! Do you think we should fix the version as datafusion v11 just released? I used master since v10 has some issues to pass the tests

That might be a good one. We might also install just the latest stable version of datafusion-cli.

**Comment by waitingkuo** [comment]
@Dandandan  do you know whether installing from `cargo install datafusion-cli` contains the flag u added?

**Comment by Dandandan** [comment]
> @Dandandan  do you know whether installing from `cargo install datafusion-cli` contains the flag u added?

Yes, those flags are for cargo, it works with building from the crates.io repository as well.

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
