### PR TITLE
Add Cloudberry DB

### PR DESCRIPTION
**Pull request by kapustor**
This PR adds test script and result for Cloudberry DB - a fork of Greenplum DB rebased on PG 14. The initial test was run on AWS machine c6a.4xlarge.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tuhaihe** [comment]
Hi @kapustor I'm Dianjin from the [Cloudberry Database community](https://github.com/cloudberrydb/cloudberrydb). Thanks for your work to add Cloudberry DB support to the ClickBench!

**Comment by kapustor** [comment]
Hey @tuhaihe , of course! I spent many years working with Greenplum, first as a DBA, and then as a product manager. Though I am not connected with this database anymore, I still love the community :)

**Comment by tuhaihe** [comment]
Cool!

As you may know, Greenplum was archived this past May and has gone closed-source (https://github.com/greenplum-db/gpdb-archive). This was disappointing news for the original Greenplum community. However, we're actively working on taking Cloudberry to a third-party foundation to prevent this from happening again. 

My friend, stay tuned for good news in the coming weeks! 

Thanks for your support again!

**Comment by alexey-milovidov** [comment]
This is really good news, happy to see ex-Greenplum in good hands!

**Pull request merged**
