### PR TITLE
updated for datafusion release 43.0.0

### PR DESCRIPTION
**Pull request by pmcgleenon**
This PR updates the datafusion Clickbench results for [release 43.0.0](https://github.com/apache/datafusion/releases/tag/43.0.0)

Ran the benchmarks on an EC2 instance described in the [README](https://github.com/ClickHouse/ClickBench/blob/main/datafusion/README.md): c6a.4xlarge, 500gb gp2 running Amazon Linux 2 AMI

### CODE REVIEW

**Comment by pmcgleenon** [comment]
@rschu1ze @alexey-milovidov   👋 Happy Friday everyone!  here's the updated results for the latest DataFusion release

**Comment by rschu1ze** [comment]
@pmcgleenon Happy Friday and thanks a lot. I made only a small fixup commit which removed the changes in index.html. CI wil automatically update index.html based on the result JSON files.

**Comment by rschu1ze** [comment]
(the update takes a couple of minutes)

**Comment by pmcgleenon** [comment]
Good to know, thanks for the quick turn-around!

**Pull request merged**
