### PR TITLE
Mongo optimizations

### PR DESCRIPTION
**Pull request by mosinnik**
Add indexes and rework queries. Some queries was fixed. 
Can't make results on AWS and here I need help.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok. I'm trying to run it on a VM.
Loading became slower (it spend about three hours at 78%).
I hope queries will become faster. I will add a new result...

**Comment by mosinnik** [comment]
of cause indexes impact import stage. And I forgot to add parameter `--numInsertionWorkers=16` to mongoimport. By default mongoimport use one worker.

**Comment by alexey-milovidov** [comment]
Now the loading is at 97.9%. It will be sad if I will have to start over...

**Comment by alexey-milovidov** [comment]
`real    747m3.958s`

**Comment by alexey-milovidov** [comment]
```
$ sudo du -bcs /var/lib/mongodb/
86397751448     /var/lib/mongodb/
86397751448     total
```

**Comment by alexey-milovidov** [comment]
I will continue to provide updates, as it appeared to be longer than expected.

The latest news: I forgot to run it in screen:
```
$ time mongosh --quiet ./run.js | tee result.json
{"q":0,"it":0,"ok":1,"t":68201,"res":[{"c":99997497}]}
{"q":0,"it":1,"ok":1,"t":65840,"res":[{"c":99997497}]}
{"q":0,"it":2,"ok":1,"t":66851,"res":[{"c":99997497}]}
{"q":1,"it":0,"ok":1,"t":704,"res":[{"c":630500}]}
{"q":1,"it":1,"ok":1,"t":487,"res":[{"c":630500}]}
{"q":1,"it":2,"ok":1,"t":418,"res":[{"c":630500}]}
{"q":2,"it":0,"ok":1,"t":141572,"res":[{"_id":null,"sum_AdvEngineID":7280088,"c":99997497,"avg_ResolutionWidth":1513.4879349030107}]}
{"q":2,"it":1,"ok":1,"t":120438,"res":[{"_id":null,"sum_AdvEngineID":7280088,"c":99997497,"avg_ResolutionWidth":1513.4879349030107}]}
{"q":2,"it":2,"ok":1,"t":120302,"res":[{"_id":null,"sum_AdvEngineID":7280088,"c":99997497,"avg_ResolutionWidth":1513.4879349030107}]}
{"q":3,"it":0,"ok":1,"t":109463,"res":[{"_id":null,"a":{"$numberDecimal":"2528953029789715941.464149637665431"}}]}
{"q":3,"it":1,"ok":1,"t":93122,"res":[{"_id":null,"a":{"$numberDecimal":"2528953029789715941.464149637665431"}}]}
{"q":3,"it":2,"ok":1,"t":94238,"res":[{"_id":null,"a":{"$numberDecimal":"2528953029789715941.464149637665431"}}]}
{"q":4,"it":0,"ok":1,"t":29430,"res":[{"c":17630976}]}
{"q":4,"it":1,"ok":1,"t":26520,"res":[{"c":17630976}]}
{"q":4,"it":2,"ok":1,"t":25548,"res":[{"c":17630976}]}
{"q":5,"it":0,"ok":1,"t":20077,"res":[{"c":6019103}]}
{"q":5,"it":1,"ok":1,"t":10097,"res":[{"c":6019103}]}
{"q":5,"it":2,"ok":1,"t":10227,"res":[{"c":6019103}]}
{"q":6,"it":0,"ok":1,"t":20,"res":[{"_id":null,"min":{"$date":"2013-07-02T00:00:00Z"},"max":{"$date":"2013-07-31T00:00:00Z"}}]}
{"q":6,"it":1,"ok":1,"t":3,"res":[{"_id":null,"min":{"$date":"2013-07-02T00:00:00Z"},"max":{"$date":"2013-07-31T00:00:00Z"}}]}
{"q":6,"it":2,"ok":1,"t":3,"res":[{"_id":null,"min":{"$date":"2013-07-02T00:00:00Z"},"max":{"$date":"2013-07-31T00:00:00Z"}}]}
{"q":7,"it":0,"ok":1,"t":672,"res":[{"_id":2,"c":404602},{"_id":27,"c":113167},{"_id":13,"c":45631},{"_id":45,"c":38960},{"_id":44,"c":9730},{"_id":3,"c":6896},{"_id":62,"c":5266},{"_id":52,"c":3554},{"_id":50,"c":938},{"_id":28,"c":836},{"_id":53,"c":350},{"_id":25,"c":343},{"_id":61,"c":158},{"_id":21,"c":38},{"_id":42,"c":20},{"_id":16,"c":7},{"_id":7,"c":3},{"_id":22,"c":1}]}
{"q":7,"it":1,"ok":1,"t":689,"res":[{"_id":2,"c":404602},{"_id":27,"c":113167},{"_id":13,"c":45631},{"_id":45,"c":38960},{"_id":44,"c":9730},{"_id":3,"c":6896},{"_id":62,"c":5266},{"_id":52,"c":3554},{"_id":50,"c":938},{"_id":28,"c":836},{"_id":53,"c":350},{"_id":25,"c":343},{"_id":61,"c":158},{"_id":21,"c":38},{"_id":42,"c":20},{"_id":16,"c":7},{"_id":7,"c":3},{"_id":22,"c":1}]}
{"q":7,"it":2,"ok":1,"t":647,"res":[{"_id":2,"c":404602},{"_id":27,"c":113167},{"_id":13,"c":45631},{"_id":45,"c":38960},{"_id":44,"c":9730},{"_id":3,"c":6896},{"_id":62,"c":5266},{"_id":52,"c":3554},{"_id":50,"c":938},{"_id":28,"c":836},{"_id":53,"c":350},{"_id":25,"c":343},{"_id":61,"c":158},{"_id":21,"c":38},{"_id":42,"c":20},{"_id":16,"c":7},{"_id":7,"c":3},{"_id":22,"c":1}]}
client_loop: send disconnect: Broken pipe
```

**Comment by alexey-milovidov** [comment]
Update: it still running.

**Comment by alexey-milovidov** [comment]
All queries were run, `real    1002m2.063s`

**Comment by alexey-milovidov** [comment]
The result is good, it is almost 10 times faster:
Screenshot_20221025_213616

**Comment by alexey-milovidov** [comment]
Now we will have to re-run the import to measure the loading time again...

**Comment by mosinnik** [comment]
nice, but something going wrong with Q30 and Q31 - they should took lees time by index usage . Anyway total result is good

**Comment by alexey-milovidov** [comment]
Trying to import it again to measure the time with parallel loading enabled...

**Comment by alexey-milovidov** [comment]
At 67% now. Parallelism does not help as it is bounded by IO and it is doing a lot of random access.

**Comment by alexey-milovidov** [comment]
At 83% now.

**Comment by alexey-milovidov** [comment]
real    940m27.266s

**Comment by alexey-milovidov** [comment]
Looks like parallel loading is slower than single-threaded loading. I will leave the best result.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Published.

**Pull request merged**
