### PR TITLE
add SelectDB result

### PR DESCRIPTION
**Pull request by hello-stephen**
[SelectDB](https://selectdb.com/), the enterprise-grade cloud-native distribution for [Apache Doris](https://github.com/apache/doris).

### CODE REVIEW

**Comment by hello-stephen** [comment]
@alexey-milovidov hi, please take review if you are available and if any problem with the result, please let me know, thanks.

**Review by alexey-milovidov — APPROVED** [review]
Reproduced the results, all perfect :+1:

**Comment by alexey-milovidov** [comment]
FYI reproduced result is
```
{
    "system": "SelectDB",
    "date": "2022-10-08",
    "machine": "c6a.4xlarge, 500gb gp2",
    "cluster_size": 1,
    "comment": "",
    "tags": ["C++", "column-oriented", "MySQL compatible"],
    "load_time": 529,
    "data_size": 17122688838,
    "result": [
[0.04,0.03,0.02],
[0.13,0.03,0.03],
[0.13,0.04,0.05],
[1.04,0.05,0.06],
[0.36,0.34,0.33],
[0.96,0.68,0.67],
[0.02,0.02,0.02],
[0.03,0.03,0.03],
[0.63,0.62,0.61],
[0.61,0.69,0.68],
[0.47,0.14,0.14],
[0.20,0.16,0.16],
[0.62,0.61,0.57],
[0.98,1.02,1.04],
[0.91,0.87,0.88],
[0.37,0.37,0.36],
[1.26,1.24,1.24],
[0.29,0.25,0.33],
[2.50,2.30,2.32],
[0.02,0.01,0.01],
[10.75,1.16,1.13],
[9.70,2.14,0.95],
[11.97,1.20,1.03],
[5.73,0.35,0.28],
[0.12,0.05,0.04],
[0.35,0.15,0.15],
[0.04,0.05,0.04],
[9.27,1.92,1.24],
[8.82,2.92,2.87],
[0.68,0.59,0.60],
[1.77,0.43,0.42],
[2.30,0.49,0.50],
[3.03,3.16,3.46],
[11.72,4.46,4.40],
[12.09,4.37,4.46],
[0.53,0.48,0.48],
[0.10,0.06,0.07],
[0.04,0.04,0.04],
[0.03,0.03,0.02],
[0.16,0.13,0.13],
[0.06,0.03,0.03],
[0.04,0.02,0.02],
[0.04,0.03,0.02]
    ]
}
```

Slightly longer loading time. But overall the numbers look very similar.

**Comment by hello-stephen** [comment]
> @hello-stephen Could you also please add Apache Doris? It should be easy after SelectDB and Starrocks.

OK, I'll submit the result later.

**Comment by amosbird** [comment]
I think the result should also be tagged with `ClickHouse derivative`. (Also true for Apache Doris if it will be added)

**Comment by alexey-milovidov** [comment]
Yes, Doris has a bunch of derivative code from ClickHouse, let's add this tag.

**Comment by alexey-milovidov** [comment]
We've also checked on a larger server and for some reason, the results are relatively worse: https://github.com/ClickHouse/ClickBench/pull/38

**Comment by alexey-milovidov** [comment]
@hello-stephen we still want to see Doris in the list :)

**Comment by hello-stephen** [comment]
> 

Doris is preparing to release version 1.2 recently, and I intend to submit the results of this version.

**Comment by hello-stephen** [comment]
> @hello-stephen we still want to see Doris in the list :)

Doris is preparing to release version 1.2 recently, and I intend to submit the results of this version.

**Pull request merged**
