### PR TITLE
update results of databend

### PR DESCRIPTION
**Pull request by sundy-li**
Changes of this pr:

1. bench it with the latest `v0.8.111` version, now it can pass all queries.
2. make bench scripts simple
3. update the readme

It's not fast enough but worth to update.

### CODE REVIEW

**Comment by sundy-li** [comment]
OMG, I just notice it's tested on gp3, I'll fix this later.

**Comment by sundy-li** [comment]
cc @alexey-milovidov  PTAL

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thank you!

**Comment by alexey-milovidov** [comment]
The results are much better than before, like 5 times!

**Pull request merged**
