### PR TITLE
[CelerData] Add CelerData test results

### PR DESCRIPTION
**Pull request by chaoyli**
Thank you for the contribution!

Please make sure that you've updated `index.html`. In order to do this run `generate-results.sh` from the root directory of ClickBench repository.

### CODE REVIEW

**Comment by melvynator** [comment]
@chaoyli I've tried to repro, but it seems that you do not expose the required instance type for me to repro this performance. 

I used the classic cluster (needs to be specified in the benchmark):

image

In your benchmark, you chose: `c6a.metal`

But in the UI, you only provide access to general-purpose or memory-optimized instances. 

Will it be possible for you to enable it for me? Will I have enough free credits to test it? 

Here is my account name and ID `clickbench-repro	v8d12dxde`

Also, what are your recommendations for:

BE Storage
BE Node count (`"cluster_size": 1` shall it be one?)

It isn't specified in the readme. 

`CelerData Cloud Cloud` should probably be changed to `CelerData Cloud`, `CelerData Cloud Classic`, `CelerData BYOC`, `CelerData Bring Your Own Cloud` or something more clear than `Cloud Cloud`

**Comment by melvynator** [comment]
@chaoyli 

```
curl --location-trusted \
    -u root: \
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    http://$Endpoint/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
echo "Load data costs $LOADTIME seconds"
```
I suspect you forgot to add the credentials:

```
curl --location-trusted \
    -u $admin:$password \
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    http://$Endpoint/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
echo "Load data costs $LOADTIME seconds"
```

Do you need to add the port/or modify VPC inbound settings?

**Comment by chaoyli** [comment]
Hello, @melvynator , thanks for your reply.
I test in the BYOC/classic cluster. `c6a.metal` is available in the `us-west-2`
image

**Comment by chaoyli** [comment]
Hello, @melvynator , thanks for your reply.
I test in the Cloud Private and classic cluster. 
1. `c6a.metal` is available in the `us-west-2`
image

2. The test is for one BE and one FE.
m6i.2xlarge as FE, c6a.metal as BE

3. After the cluster is created. There will be a `endopoint` in the website.  You can use this endpoint to connect and ingest data into starrocks. There is no need to use the port. It will auto proxy the port.
image

4. What's credit are you using for this account `clickbench-repro`?

**Comment by melvynator** [comment]
https://github.com/ClickHouse/ClickBench/assets/5473562/460a6d01-73e3-4c75-828d-e73f8303a203

As you can see, I do not have access to this type of machine. 



```
START=$(date +%s)
echo "Start to load data..."
curl --location-trusted \
    -u [redacted]:[redacted]\
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    http://xedr9ibmy.cloud-app.celerdata.com/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
echo "Load data costs $LOADTIME seconds"
Start to load data...

curl: (28) Failed to connect to xedr9ibmy.cloud-app.celerdata.com port 80 after 130124 ms: Connection timed out
Load data costs 130 seconds
```

Some network-related configurations must be missing. I can connect via the MySQL client:

```
mysql -h xedr9ibmy.cloud-app.celerdata.com -P9030 -u[redacted] -p[redacted] -e "SELECT count(*) FROM hits.hits"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

Did you have to change your network related settings used by the VPC?

**Comment by melvynator** [comment]
@chaoyli Did you used a whole new VPC or an existing one when you created your service?

**Comment by allencelerdata** [comment]
Hello, @melvynator .1. `c6a.metal` is in the `us-west-2` region.

**Comment by chaoyli** [comment]
@melvynator Sorry for the late reply. I have updated the info. Be grateful test again.
1. `c6a.metal` is on the `us-west-2`. 
2. Also, it's better to start the test EC2 in `us-west-2` to reduce the network transportation time when send query and return results. 
3. Use `https` to replace `http` in the `http://xedr9ibmy.cloud-app.celerdata.com/api/hits/hits/_stream_load`
4. The port is not necessary in the BYOC

**Comment by melvynator** [comment]
> 1. c6a.metal is on the us-west-2.
Indeed I see it now, for some reason the default region was in APJ.

> Also, it's better to start the test EC2 in us-west-2 to reduce the network transportation time when send query and return results.

My instance is in this region. 

With https:

```
START=$(date +%s)
echo "Start to load data..."
curl --location-trusted \
    -u [redacted]:[redacted] \
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    https://$endpoint/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
echo "Load data costs $LOADTIME seconds"


<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
Load data costs 0 seconds
```

**Comment by melvynator** [comment]
image

For some reason the service is now degraded

**Comment by melvynator** [comment]
Maybe this is the RC:

image

**Comment by melvynator** [comment]
The `FE Nodes` seems to be now crashlooping. Will recreate a service.

**Comment by melvynator** [comment]
Ok made some progress after recreating a service

```
 echo "Start to load data..."
curl --location-trusted \
    -u [redacted]:[redacted] \
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    https://$endpoint/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
```

```
Start to load data...
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
Load data costs 5224 seconds
```
I can see some data being loaded:

image

But running:

```
mysql -h $endpoint -P 9030 -uadmin -p[redacted] -e "SELECT count(*) FROM hits.hits"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

**Comment by melvynator** [comment]
😢 
image

```
curl --location-trusted \
    -u admin:[redacted] \
    -T "hits.tsv" \
    -H "label:hits_tsv_${START}" \
    -H "columns: WatchID,JavaEnable,Title,GoodEvent,EventTime,EventDate,CounterID,ClientIP,RegionID,UserID,CounterClass,OS,UserAgent,URL,Referer,IsRefresh,RefererCategoryID,RefererRegionID,URLCategoryID,URLRegionID,ResolutionWidth,ResolutionHeight,ResolutionDepth,FlashMajor,FlashMinor,FlashMinor2,NetMajor,NetMinor,UserAgentMajor,UserAgentMinor,CookieEnable,JavascriptEnable,IsMobile,MobilePhone,MobilePhoneModel,Params,IPNetworkID,TraficSourceID,SearchEngineID,SearchPhrase,AdvEngineID,IsArtifical,WindowClientWidth,WindowClientHeight,ClientTimeZone,ClientEventTime,SilverlightVersion1,SilverlightVersion2,SilverlightVersion3,SilverlightVersion4,PageCharset,CodeVersion,IsLink,IsDownload,IsNotBounce,FUniqID,OriginalURL,HID,IsOldCounter,IsEvent,IsParameter,DontCountHits,WithHash,HitColor,LocalEventTime,Age,Sex,Income,Interests,Robotness,RemoteIP,WindowName,OpenerName,HistoryLength,BrowserLanguage,BrowserCountry,SocialNetwork,SocialAction,HTTPError,SendTiming,DNSTiming,ConnectTiming,ResponseStartTiming,ResponseEndTiming,FetchTiming,SocialSourceNetworkID,SocialSourcePage,ParamPrice,ParamOrderID,ParamCurrency,ParamCurrencyID,OpenstatServiceName,OpenstatCampaignID,OpenstatAdID,OpenstatSourceID,UTMSource,UTMMedium,UTMCampaign,UTMContent,UTMTerm,FromTag,HasGCLID,RefererHash,URLHash,CLID" \
    https://$endpoint/api/hits/hits/_stream_load
END=$(date +%s)
LOADTIME=$(echo "$END - $START" | bc)
echo "Load data costs $LOADTIME seconds"
Start to load data...
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```

I can't log to the service anymore.

**Comment by chaoyli** [comment]
@melvynator Do you have shutdown the `test-clickbench` cluster?

**Comment by melvynator** [comment]
@chaoyli As discussed during our call, I will hold review on this PR until we have a more turnkey script and reproducible benchmark:

1. Scripts need to be improved 
- There are a lot of issues with the script, http, instead of https, data downloaded in the wrong folder for the script to be executed without issue
2. Missing read me information
- No information about the region you need to deploy in (some region don't have the recommended hardware)
- No information about the sizing of the disk or FE size etc...
3. The replication of the benchmark needs to be straightforward:
- I should just be able to follow the readme for the manual steps right now. This was challenging; I had to figure out why the FE node was crashing (not enough disk space); I workaround it by using 3 FE nodes, I couldn't load the data because of missing info in the scripts, it took me quite some time to be able to figure out all the issues.  
- The data loading time is not reproduced on my side and is at least 2 X slower
- There are no cold queries in my replication, and there seems to be no way of reproducing cold/hot queries because some cache layer is not removed correctly in the script.

**Comment by melvynator** [comment]
No update since a while ago. Closing.

**Pull request closed without merging**
